name: 🐞 Bug
description: Signaler un comportement inattendu ou une erreur
labels: [bug, triage]
body:
  - type: textarea
    attributes:
      label: Description du bug
      description: Explique clairement ce qui ne fonctionne pas.
      placeholder: "Quand je clique sur Connexion, l'app crashe..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Étapes pour reproduire
      description: Explique comment reproduire le bug.
      placeholder: |
        1. Aller sur l'écran d'accueil
        2. Cliquer sur le bouton Connexion
        3. Entrer des identifiants
        4. Voir l'erreur
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comportement attendu
      description: Que devait-il se passer selon toi ?
      placeholder: "L'utilisateur devait être redirigé vers l'écran d'accueil."

  - type: input
    attributes:
      label: Plateforme concernée
      placeholder: "iOS 17.4, macOS 14.3, Android 13..."

  - type: input
    attributes:
      label: Version de l'app
      placeholder: "v1.0.3 (build 72)"
