name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 <title>"
labels: ["bug"]
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: bash
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: "Platform"
      description: What platform(s) do you see the problem on?
      multiple: true
      options:
        - Android
        - iOS
        - Linux
        - Windows
        - Macos
        - Web
    validations:
      required: true
  - type: input
    attributes:
      label: App Version
      description: What version of Hessflix are you using?
      placeholder: e.g. v0.2.1 (25) or just v0.2.1
