blank_issues_enabled: false
contact_links:
  - name: "💡 Feature Request"
    url: "https://github.com/DonutWare/Hessflix/discussions/new?category=ideas"
    about: "Suggest a new feature or enhancement."
